@authToken=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InBpc3VuMkBnbWFpbC5jb20iLCJpYXQiOjE2MTgyNjk4ODV9.PSgFGkaIRcZeMvbbBsAi3pyJvqr9Fw0-n1iVfxhITHeHJKpu9XxBLg2zeWila3oKG9Co2C8p7hK4RcoHz2T3Rz_AN_IR1kkxzx0KoSH70_m1LEGLeqN4FHqPWaeZ1fGfI6pG6aLzsZB6P_8qizZ9fLRlPIi5wksOfx1QWR3ugo8
## {{$dotenv TEST_AUTH_TOKEN}} you can use 

### Get all boards
GET http://localhost:3000/api/boards HTTP/1.1
Authorization: {{authToken}}

### Create Card
POST http://localhost:3000/api/boards HTTP/1.1
Authorization: {{authToken}}
content-type: application/json

{
  "title": "demo project",
  "description": "this should be fast"
}

### get detail
GET http://localhost:3000/api/boards/607318cbe6602dad5381bc48 HTTP/1.1
Authorization: {{authToken}}

### DELETE BOARD
DELETE  http://localhost:3000/api/boards/607318cae6602dad5381bc47 HTTP/1.1
Authorization: {{authToken}}

### Get all cards
GET http://localhost:3000/api/cards/b/1 HTTP/1.1
Authorization: {{authToken}}

### Create Card
POST http://localhost:3000/api/cards HTTP/1.1
Authorization: {{authToken}}
content-type: application/json

{
  "board_id": 1,
  "title": "working on api",
  "description": "this should be fast",
  "status": "TODO"
}

### Find card by id
GET http://localhost:3000/api/cards/6073248a226090b9e92ad2d1 HTTP/1.1
Authorization: {{authToken}}

### update Card
PUT http://localhost:3000/api/cards/6074c583dfa89004e78a790e HTTP/1.1
Authorization: {{authToken}}
content-type: application/json

{
  "title": "demo project",
  "description": "this should be fast =========="
}