### Get all boards
GET http://localhost:3000/api/boards HTTP/1.1
Authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InBpc3VuMkBnbWFpbC5jb20iLCJpYXQiOjE2MTgxNzE4NzV9.RJdRyFrKtttuf9gPBiUMdD0SotNp6qlLN676rhrGHecLMmJ0hBDOWodKJwyukW-xE5YS_YVjHCKv3b9qrBgDxOMwQBDJsPc7axuxukbmJnZg_EAi18UMXAuXCFfu3ukJsBPjjblijgug4yjpDl393-0nAmnd5PMmeVdbqoc2V9g

### Create Card
POST http://localhost:3000/api/boards HTTP/1.1
Authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBpc3VuMiIsInBhc3N3b3JkIjoiJDJiJDEwJG55cWQ1dlJ5UG14bjh4cVByb2pyaC5ESTNjNUJLbVBWWFVLUldSL2s0d3BZRTBna09ERE5lIiwiaWF0IjoxNjE3OTIzNDI0fQ.NYZRSB4aaqdoUFfQHO84BkeYw3jQSZTBklNVI_Qs_PJrVM_3BqhbyLOy-nZ56Fg-kYeuD6qCHS8Nd1zmjsz24aCAQYJGzlfuyoZqkEabLA_hyMrfjrczFa1JR29EZn6KQLe3Gp4O_nX5W_ccXpFUrV6TTcUnGuMy04M4_6pSMh8
content-type: application/json

{
  "title": "demo project",
  "description": "this should be fast"
}

### get detail
GET http://localhost:3000/api/boards/607318cbe6602dad5381bc48 HTTP/1.1
Authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InBpc3VuMkBnbWFpbC5jb20iLCJpYXQiOjE2MTgxNzExODd9.wWuglF3fr2kYNTTluiKnae3DW3jaLF9vqV3TSWP6d33II9nAV9xF9PzkgP4R4tGKDQeSL-K9rdgXId6uiQByE190CF3TZ6FB5VfEeFgBsCqCOT0rf_uLXbpzWoIxf2OAufthOF53Q9XIfKMcHnLCwVi01hTE2VBX1bfIWyKD5Ms

### DELETE BOARD
DELETE  http://localhost:3000/api/boards/607318cae6602dad5381bc47 HTTP/1.1
Authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InBpc3VuMkBnbWFpbC5jb20iLCJpYXQiOjE2MTgxNzExODd9.wWuglF3fr2kYNTTluiKnae3DW3jaLF9vqV3TSWP6d33II9nAV9xF9PzkgP4R4tGKDQeSL-K9rdgXId6uiQByE190CF3TZ6FB5VfEeFgBsCqCOT0rf_uLXbpzWoIxf2OAufthOF53Q9XIfKMcHnLCwVi01hTE2VBX1bfIWyKD5Ms

### Get all cards
GET http://localhost:3000/api/cards HTTP/1.1
Authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InBpc3VuMkBnbWFpbC5jb20iLCJpYXQiOjE2MTgxNzExODd9.wWuglF3fr2kYNTTluiKnae3DW3jaLF9vqV3TSWP6d33II9nAV9xF9PzkgP4R4tGKDQeSL-K9rdgXId6uiQByE190CF3TZ6FB5VfEeFgBsCqCOT0rf_uLXbpzWoIxf2OAufthOF53Q9XIfKMcHnLCwVi01hTE2VBX1bfIWyKD5Ms

### Create Card
POST http://localhost:3000/api/cards HTTP/1.1
Authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InBpc3VuMkBnbWFpbC5jb20iLCJpYXQiOjE2MTgxNzExODd9.wWuglF3fr2kYNTTluiKnae3DW3jaLF9vqV3TSWP6d33II9nAV9xF9PzkgP4R4tGKDQeSL-K9rdgXId6uiQByE190CF3TZ6FB5VfEeFgBsCqCOT0rf_uLXbpzWoIxf2OAufthOF53Q9XIfKMcHnLCwVi01hTE2VBX1bfIWyKD5Ms
content-type: application/json

{
  "board_id": 1,
  "title": "working on api",
  "description": "this should be fast",
  "status": "TODO"
}

### Find card by id
GET http://localhost:3000/api/cards/6073248a226090b9e92ad2d1 HTTP/1.1
Authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBpc3VuMiIsInBhc3N3b3JkIjoiJDJiJDEwJG55cWQ1dlJ5UG14bjh4cVByb2pyaC5ESTNjNUJLbVBWWFVLUldSL2s0d3BZRTBna09ERE5lIiwiaWF0IjoxNjE3OTIzNDI0fQ.NYZRSB4aaqdoUFfQHO84BkeYw3jQSZTBklNVI_Qs_PJrVM_3BqhbyLOy-nZ56Fg-kYeuD6qCHS8Nd1zmjsz24aCAQYJGzlfuyoZqkEabLA_hyMrfjrczFa1JR29EZn6KQLe3Gp4O_nX5W_ccXpFUrV6TTcUnGuMy04M4_6pSMh8